version: "3"

services:
  gestao-colaborador:
     image: bitnami/postgresql
     ports:
      - 5432:5432
     environment:
     - POSTGRESQL_USERNAME=docker
     - POSTGRESQL_PASSWORD=docker
     - POSTGRESQL_DATABASE=gestaocolaborador